blog/urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
]

blogproject/urls.py
from django.conf.urls import include, url
from django.contrib import admin
admin.autodiscover()
from django.conf import settings

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blog.urls',namespace='blog')),
    url(r'', include('comments.urls',namespace='comments')),
    url(r'^upload/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
]

comments/urls.py
from django.conf.urls import url

from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blog/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.utils.six import python_2_unicode_compatible
from django.core.urlresolvers import reverse

class Category(models.Model):	
    """
    django 要求我们必须继承 models.Model 类，
    Category 只需要一个简单的分类名 name 就可以了。

    CharField 指定了 name 的数据类型，
    CharField 是字符型，
    max_length 指定其最大长度，
    超过这个长度的分类名就不能被存入数据库。

    当然 django 还为我们提供了各种各样的类型，
    如日期时间类型 DateTimeField、
    整数类型 IntegerField 等等。
    django 内置的类型全部类型可查看文档：
    https://docs.djangoproject.com/en/1.10/ref/models/fields/#field-types
    """
    name = models.CharField(max_length=100)


    def __str__(self):
        # python_2_unicode_compatible 装饰器用于兼容 Python2
        return self.name


class Tag(models.Model):
    """
    标签 Tag 也比较简单，
    和 Category 一样。
    再次强调一定要继承 models.Model 类！
    """
    name = models.CharField(max_length=100)


    def __str__(self):
        # python_2_unicode_compatible 装饰器用于兼容 Python2
        return self.name


class Post(models.Model):
    """
    文章的数据库表稍微复杂一点，主要是涉及的字段更多。
    """

    # 文章标题
    title = models.CharField(max_length=70)

    # 文章正文，我们使用了 TextField。
    # 比较短的字符串存储可以使用 CharField，
    # 但对于文章的正文来说可能会是一大段文本，
    # 因此使用 TextField 来存储大段文本。
    body = models.TextField()

    # 这两个列分表表示了文章的创建时间和最后一次修改时间，
    # 存储时间的列用 DateTimeField。
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    # 文章摘要，可以没有文章摘要，
    # 但默认情况下 CharField 要求我们必须存入数据，
    # 否则就会报错。
    # 指定 blank=True 后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)

    # 这是分类与标签，
    # 分类与标签的模型我们已经定义在上面。
    # 我们在这里把文章对应的数据库表和分类与标签对应的表关联起来，
    # 但是关联形式稍微有点不同。
    # 我们规定一篇文章只能对应一个分类，
    # 但是一个分类下可以有很多篇文章，
    # 所以我们使用的是 ForeignKey，
    # 即一对多的关系。
    # 而对于标签来说，
    # 一篇文章可以有多个标签，
    # 同一个标签下也可能有多篇文章，
    # 所以我们使用 ManyToManyField，
    # 表明这是多对多的关系。
    # 同时我们规定文章可以没有标签，
    # 因此为标签 tags 指定了 blank=True。
    # 如果你对 ForeignKey、ManyToManyField 不了解，
    # 请看教程中的解释，
    # 亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships
    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank=True)

    # 文章作者
    # 这里 User 是从 django.contrib.auth.models 导入的。
    # django.contrib.auth 是 django 内置的应用，
    # 专门用于处理网站用户的注册、登录等流程，
    # User 是 django 为我们已经写好的用户模型，
    # 这里我们通过 ForeignKey 把文章和 User 关联起来，
    # 因为我们规定一篇文章只能有一个作者，
    # 而一个作者可能会写多篇文章，
    # 因此这是一对多的关系，
    # 和 Category 类似。
    author = models.ForeignKey(User)



    # views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)

    def increase_views(self):
        self.views += 1
        self.save(update_fields=['views'])





    def __str__(self):
        # python_2_unicode_compatible 装饰器用于兼容 Python2
        return self.title


    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})





    class Meta:
        ordering = ['-created_time','title']



class file(models.Model):
    filename = models.FileField()

    def __unicode__(self):
        return u'self.filename'

comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey('blog.Post')



    # commenting 字段记录评论数
    commenting = models.PositiveIntegerField(default=0)

    def increase_commenting(self):
        self.commenting += 1
        self.save(update_fields=['commenting'])





    def __str__(self):
        return self.text[:20]

comments/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'url', 'text']

        widgets = {
            'name': forms.TextInput(attrs={
                'placeholder': "name",
            }),
            'email': forms.TextInput(attrs={
                'placeholder': "emial",
            }),
            'url': forms.TextInput(attrs={
                'placeholder': "url",
            }),
         
        }

blog/views.py
# -*- coding: utf-8 -*-
import markdown

from django.shortcuts import render, get_object_or_404

from .models import Post

from comments.forms import CommentForm


def index(request):
    post_list = Post.objects.all().order_by('-created_time')
    return render(request, 'index.html', context={'post_list': post_list})


def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)


    # 阅读量 +1
    post.increase_views()

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                     'markdown.extensions.extra',
                                     'markdown.extensions.codehilite',
                                     'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all()
    context = {'post': post,
               'form': form,
               'comment_list': comment_list
               }
    return render(request, 'detail.html', context=context)

comments/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm


def post_comment(request, post_pk):
    # 先获取被评论的文章，因为后面需要把评论和被评论的文章关联起来
    # 这里我们使用了 django 提供的一个快捷函数 get_object_or_404
    # 这个函数的作用是当获取的文章（Post）存在时，则获取；否则返回 404 页面给用户
    post = get_object_or_404(Post, pk=post_pk)



    # http 请求有 get 和 post 两种方法，一般用户通过表单提交数据都是通过 post 请求，
    # 因此只有当用户的请求为 post 时才需要处理表单数据
    if request.method == 'POST':
        # 用户提交的数据存在 request.POST
        # 我们利用这些数据构造了 CommentForm 的实例，这样 django 的表单就生成了
        form = CommentForm(request.POST)

        # 当调用 form.is_valid() 方法时，django 自动帮我们检查表单的数据是否符合格式要求
        if form.is_valid():
            # 检查到数据是合法的，调用表单的 save 方法保存数据到数据库
            # commit=False 的作用是仅仅利用表单的数据生成 Comment 模型类的实例
            # 但还不保存数据到数据库
            comment = form.save(commit=False)
            # 将评论和被评论的文章关联起来
            comment.post = post
            # 最终将评论数据保存进数据库，调用模型实例的 save 方法
            comment.save()




            #评论数 +1
            comment.increase_commenting()




            # 重定向到 post 的详情页
            return redirect(post)

        else:
            # 检查到数据不合法，重新渲染详情页，并且渲染表单的错误
            # 因此我们传了三个模板变量给 detail.html
            # 一个是文章（Post），一个是评论列表，一个是表单 form
            # 注意这里我们用到了 post.comment_set.all() 方法
            # 这个用法有点类似于 Post.objects.all()
            # 其作用是获取这篇 post 下的的全部评论
            # 因为 Post 和 Comment 是 ForeignKey 关联的
            # 因此使用 post.comment_set.all() 反向查询全部评论
            # 正向查询就直接是 comment.post
            comment_list = post.comment_set.all()
            context = {'post': post,
                       'form': form,
                       'comment_list': comment_list
                       }
            return render(request, 'detail.html', context=context)
    # 不是 post 请求，说明用户没有提交数据，重定向到文章详情页
    return redirect(post)

templates/base.html
{% load blog_tags %}
<!DOCTYPE html>
<html>
	<head>
		<title>鸟不会飞</title>

		<!-- meta -->
		<meta charset="UTF-8">
	    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	    {% load staticfiles %}

	    <!-- css -->
    	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style.css' %}">
    	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style1.css' %}">
    	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style2.css' %}">
    	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/style3.css' %}">
    	<link rel="stylesheet" type="text/css" href="{% static 'blog/css/font-awesome-4.6.3/css/font-awesome.min.css' %}">

	    <!-- js 
	    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    	<script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    	<script src="{% static 'blog/js/pace.min.js' %}"></script>
    	<script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    	-->

    	
	</head>
	<body>
		<div class="container">	
			<header id="site-header">
				<div class="logo">
					<div id="logo"><a href="{% url 'blog:index' %}">鸟不会飞</a></div>
					<div id="signature">一只没有放弃蹦跶的菜鸟...  <a class="list-group-item" href="#"><i class="fa fa-twitter"></i></a></div>
				</div>
				<div id="daohang">
  					<ul class="navbar-right">
  						<li class="cl-effect-11"><a href="#" data-hover="Contact">Contact</a></li>
  						<li class="cl-effect-11"><a href="#" data-hover="About">About</a></li>
  						<li class="cl-effect-11"><a href="#" data-hover="Blog">Blog</a></li>
    					<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="Home">Home</a></li>	
  					</ul>
				</div><!-- col-md-8 -->
			</header>
		</div>
		<div id="butn" ><a href="#" onClick="daohangchange('daohang_1','butn')" ><i class="fa fa-navicon"></i></a></div>
		<div id="daohang_1">	
			<ul class="navbar-right">
				<li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="Home">Home</a></li>
  				<li class="cl-effect-11"><a href="#" data-hover="About">About</a></li>
  				<li class="cl-effect-11"><a href="#" data-hover="Contact">Contact</a></li>
  				<li class="cl-effect-11"><a href="#" data-hover="Blog">Blog</a></li>		
  			</ul>
		</div>
		<div class="content-body">
			<div class="container-body">
				<div class="row">
					<main class="col-md-8">
    					{% block main %}
    					{% endblock main %}
					</main>
					<aside id="col-md-4">

						<div class="widget widget-message">
							<div class="head_1">
								<img src="/static/blog/img/me.png">
							</div>
							<h4 class="signature_1">最美好的场景就是…</h4>
						</div>

						<div class="widget widget-recent-posts">		
							<h3 class="widget-title"><i class="fa fa-clock-o"></i> Recent Posts</h3>	
							{% get_recent_posts as recent_post_list %}	
							<ul>
									{% for post in recent_post_list %}
        							<li>
            							<a href="{{ post.get_absolute_url }}">> {{ post.title }}</a>
        							</li>
        							{% endfor %}
							</ul>
						</div>

						<div class="widget widget-archives">		
							<h3 class="widget-title"><i class="fa fa-calendar-o"></i> Archives</h3>	
							{% archives as date_list %}	
							<ul>
								{% for date in date_list %}
    							<li>
      								<a href="#">> {{ date.year }} 年 {{ date.month }} 月</a>
   								</li>
    							{% endfor %}
							</ul>
						</div>

						<div class="widget widget-category">		
							<h3 class="widget-title"><i class="fa fa-tags"></i> Category</h3>		
							{% get_categories as category_list %}
  							<ul>
    							{% for category in category_list %}
    							<li>
    								<a href="#">> {{ category.name }}</a>
    							</li>
    							{% endfor %}
							</ul>
						</div>
					</aside>
				</div>
			</div>
		</div>
		<footer class="site-footer">
			<div class="col-md-12">
				<p class="copyright">Copyright&copy; 2017 flybird. All rights reserved. </p>
			</div>
		</footer>

		<!-- Mobile Menu -->

		
		
<!--
		<script src="{% static 'blog/js/script.js' %}"></script>

		<script type="text/javascript">
			function form_top(){
				document.write('<div id="form_top"><a href="#top" title="回到顶部"><div class="top_img"></div></a></div>')
			}
			form_top();
		</script>

-->
		<script type="text/javascript">
			daohangchange();
			window.onresize = function(){
                daohangchange();
            }
			function daohangchange(){
				var Box=document.body.offsetWidth;
    			var daohang=document.getElementById('daohang');
    			var daohang_1=document.getElementById('daohang_1');
    			var butn=document.getElementById('butn');
    			var signature=document.getElementById('signature');
    			var col=document.getElementById('col-md-4');

 
    			if (Box<480){
    				daohang.style.display="none";
    				signature.style.display="none";
    				col.style.display="none";
    				butn.style.display="";

    				if (daohang_1.style.display=="none"){
                		daohang_1.style.display="block";
            		}
            		else{
                		daohang_1.style.display="none";
                		
            		}
    				
    			}
    			else{
    				daohang_1.style.display="none";
    				butn.style.display="none";
    				daohang.style.display="";
    				col.style.display="";
    			}
    		}
    		
		</script>

	</body>
</html>

templates/detail.html
{% extends 'base.html' %}

{% block main %}

<article class="post-1">
	<header class="entry-header">
		<h1 class="entry-title">{{ post.title }}</h1>
		<div class="entry-meta">
			<span class="post-category"><a class="list-group-item" href="#"><i class="fa fa-tag"></i> {{ post.category.name }}</a></span>
			<span class="post-date"><i class="fa fa-clock-o"></i><time class="entry-date" datetime="2012-11-09T23:15:57+00:00"> {{ post.created_time }}</time></span>
			<span class="post-author"><i class="fa fa-user"></i> {{ post.author }}</span>
			<span class="comments-link"><a href="#"><i class="fa fa-commenting"></i> {{ comment.commenting }}</a></span>
			<span class="views-count"><a href="#"><i class="fa fa-eye"></i> {{ post.views }}</a></span>
		</div>
	</header>
	<div class="entry-content clearfix">
		{{ post.body|safe }}
	</div>


	<div class="comment-list">
		<h2>评论列表</h2>
		<ul class="list-unstyled">
		{% for comment in comment_list %}
			<hr class="line-1"></hr>
			<li class="comment-item">
				<span class="name">{{ comment.name }}</span>
				<time class="date">{{ comment.created_time }}</time>
				<div class="text">
					{{ comment.text }}
				</div>
			</li>
			{% empty %}
			暂无评论
		{% endfor %}
		</ul>
	</div>


	<form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
		{% csrf_token %}
		<div class="row_comment">
			<div class="col-md-5">
				{{ form.name }}
				{{ form.name.errors }}
			</div>
			<div class="col-md-5">
				{{ form.email }}
				{{ form.name.errors }}
			</div>
			<!--
			<div class="col-md-4">
				<label for="{{ form.url.id_for_label }}">Url:</label>
				{{ form.url }}
				{{ form.url.errors }}
			</div>
			-->
			<div class="col-md-5" contenteditable="true">
				{{ form.text }}
				{{ form.text.errors }}
			</div>
			<div class="button">
				<button type="submit"><span>发表评论</span></button>
			</div>
		</div>    <!-- row -->
	</form>
</article>
{% endblock main %}

templates/index.html
{% extends 'base.html' %}
{% block main %}
{% for post in post_list %}
	<article class="post-1">
		<header class="entry-header">
			<h1 class="entry-title">
				<a href="{{ post.get_absolute_url }}"> {{ post.title }}</a>
			</h1>
			<div class="entry-meta">
				<span class="post-category"><a class="list-group-item" href="#"><i class="fa fa-tag"></i> {{ post.category.name }}</a></span>
				<span class="post-date"><i class="fa fa-clock-o"></i><time class="entry-date" datetime="2012-11-09T23:15:57+00:00"> {{ post.created_time }}</time></span>
				<span class="post-author"><i class="fa fa-user"></i> {{ post.author }}</span>
				<span class="comments-link"><a href="#"><i class="fa fa-commenting"></i> {{ comment.commenting }}</a></span>
				<span class="views-count"><a href="#"><i class="fa fa-eye"></i> {{ post.views }}</a></span>
			</div>
		</header>
		<div class="entry-content clearfix">
			<p>{{ post.body|safe|truncatechars:80 }}</p>
			<div class="read-more cl-effect-14">
				<a href="{{ post.get_absolute_url }}" class="more-link">Read More <span class="meta-nav">>>></span></a>
			</div>
		</div>
	</article>
{% empty %}
	<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}

{% endblock main %}